# Generated by Django 3.2.5 on 2021-07-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=200)),
            ],
        ),
    ]
